name: IanMcCall.CODES
title: IanMcCall.CODES
repository: ianmcodes/ianmcodes.github.io
url: https://www.ianmccall.codes
markdown: kramdown
highlighter: rouge
# safe: true
lsi: false
timezone: America/Chicago
plugins:
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-github-metadata
  - jekyll-seo-tag
exclude: ["bower_components", "vendor"]

# SEO

