name: IanMcCall.CODES
markdown: kramdown
highlighter: rouge
safe: true
lsi: false
timezone: America/Chicago
gems:
- jekyll-mentions
- jemoji
- jekyll-redirect-from
- jekyll-sitemap
exclude: ["bower_componenets"]
